'use client';
import {useEffect,useRef,useState,type PointerEvent} from 'react';
import dynamic from 'next/dynamic';
const Record3D=dynamic(()=>import('./record-3d'),{ssr:false});
export type Spin={angle:number;velocity:number;invalidate:()=>void};
export default function Vinyl({art,title}:{art:string,title:string}){const root=useRef<HTMLDivElement>(null);const flat=useRef<HTMLCanvasElement>(null);const spin=useRef<Spin>({angle:0,velocity:0,invalidate:()=>{}});const drag=useRef({on:false,pointer:-1,last:0,time:0});const image=useRef<HTMLImageElement|null>(null);const raf=useRef(0);const [webgl,setWebgl]=useState(false);const reduced=useRef(false);const draw=useRef(()=>{});
useEffect(()=>{reduced.current=matchMedia('(prefers-reduced-motion: reduce)').matches;const c=document.createElement('canvas');const gl=c.getContext('webgl2');setWebgl(!!gl);gl?.getExtension('WEBGL_lose_context')?.loseContext();return()=>cancelAnimationFrame(raf.current)},[]);
useEffect(()=>{const c=flat.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;draw.current=()=>{const w=c.width,h=c.height,r=Math.min(w,h)*.435;ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(w/2,h/2);ctx.scale(1,.91);ctx.shadowColor='#38200c45';ctx.shadowBlur=25;ctx.shadowOffsetY=22;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fillStyle='#1A1A1A';ctx.fill();ctx.shadowColor='transparent';const grad=ctx.createConicGradient(-.4,0,0);grad.addColorStop(0,'#121212');grad.addColorStop(.16,'#414141');grad.addColorStop(.3,'#111111');grad.addColorStop(.66,'#333333');grad.addColorStop(.8,'#151515');grad.addColorStop(1,'#121212');ctx.fillStyle=grad;ctx.fill();for(let rr=r*.4;rr<r*.98;rr+=2.4){ctx.beginPath();ctx.arc(0,0,rr,0,Math.PI*2);ctx.strokeStyle=rr%5>2?'#ffffff15':'#00000077';ctx.lineWidth=.8;ctx.stroke()}ctx.rotate(spin.current.angle);ctx.beginPath();ctx.arc(0,0,r*.36,0,Math.PI*2);ctx.fillStyle='#E85D04';ctx.fill();if(image.current){ctx.save();ctx.clip();ctx.drawImage(image.current,-r*.36,-r*.36,r*.72,r*.72);ctx.restore()}ctx.beginPath();ctx.arc(0,0,5,0,Math.PI*2);ctx.fillStyle='#EFE9DD';ctx.fill();ctx.restore()};draw.current();const im=new Image();im.onload=()=>{image.current=im;draw.current()};im.src=art;return()=>{im.onload=null}},[art,webgl]);
const render=()=>{spin.current.invalidate();draw.current();if(root.current){root.current.dataset.angle=spin.current.angle.toFixed(3);root.current.dataset.velocity=spin.current.velocity.toFixed(3)}};
const coast=()=>{cancelAnimationFrame(raf.current);let last=performance.now();const tick=(now:number)=>{const dt=Math.min((now-last)/1000,.04);last=now;if(drag.current.on||document.hidden)return;spin.current.angle+=spin.current.velocity*dt;spin.current.velocity*=Math.exp(-2.1*dt);render();if(Math.abs(spin.current.velocity)>.008)raf.current=requestAnimationFrame(tick);else{spin.current.velocity=0;render()}};raf.current=requestAnimationFrame(tick)};
const angle=(e:PointerEvent<HTMLDivElement>)=>{const b=e.currentTarget.getBoundingClientRect();return Math.atan2((e.clientY-b.top-b.height/2)/.91,e.clientX-b.left-b.width/2)};
const down=(e:PointerEvent<HTMLDivElement>)=>{if(e.button!==0)return;cancelAnimationFrame(raf.current);e.currentTarget.setPointerCapture(e.pointerId);drag.current={on:true,pointer:e.pointerId,last:angle(e),time:e.timeStamp};spin.current.velocity=0;e.currentTarget.classList.add('dragging')};
const move=(e:PointerEvent<HTMLDivElement>)=>{const d=drag.current;if(!d.on||d.pointer!==e.pointerId)return;const a=angle(e);let delta=a-d.last;if(delta>Math.PI)delta-=Math.PI*2;if(delta<-Math.PI)delta+=Math.PI*2;const dt=Math.max((e.timeStamp-d.time)/1000,.008);spin.current.angle+=delta;spin.current.velocity=spin.current.velocity*.25+Math.max(-15,Math.min(15,delta/dt))*.75;d.last=a;d.time=e.timeStamp;render()};
const up=(e:PointerEvent<HTMLDivElement>)=>{if(drag.current.pointer!==e.pointerId)return;drag.current.on=false;e.currentTarget.classList.remove('dragging');spin.current.velocity*=Math.exp(-2.1*Math.max(0,e.timeStamp-drag.current.time)/1000);if(reduced.current)spin.current.velocity=0;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);coast()};
return <div ref={root} className="record-stage" role="group" aria-label={'Disque '+title+' — faites glisser pour tourner, ou utilisez les flèches du clavier'} tabIndex={0} data-art={art} data-angle="0" data-velocity="0" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onKeyDown={e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();spin.current.velocity=e.key==='ArrowRight'?3:-3;if(reduced.current){spin.current.angle+=spin.current.velocity*.1;spin.current.velocity=0}render();coast()}}} style={{touchAction:'none'}}>{webgl?<Record3D art={art} spin={spin}/>:<canvas ref={flat} width={900} height={800}/>}</div>}
